# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: servicio
  name: servicio-deployment
spec:
  replicas: {REPLICAS}
  selector:
    matchLabels:
      app: servicio
  template:
    metadata:
      labels:
        app: servicio
    spec:
      serviceAccountName: {SA_NAME}
      containers:
      - env:
        - name: STORAGE_NAME
          value: {PROJECT_ID}-bucket
        image: gcr.io/{PROJECT_ID}/servicio:{TEMPLATE_VERSION}
        imagePullPolicy: Always
        
        name: servicio
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15

        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
