
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: servicio
  name: servicio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio
  template:
    metadata:
      labels:
        app: servicio
    spec:
      serviceAccountName: :
      containers:
      - env:
        name: STORAGE_NAME
        value: multi-cluster-ingress-test-bucket
        image: gcr.io/multi-cluster-ingress-test/servicio:11046
        imagePullPolicy: Always
        
        name: servicio
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15

        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
