
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: servicio
  name: servicio-deployment
spec:
  replicas: {REPLICAS}
  selector:
    matchLabels:
      app: servicio
  template:
    metadata:
      labels:
        app: servicio
    spec:
      serviceAccountName: {SA_NAME}
      containers:
      - env:
        name: STORAGE_NAME
        value: {PROJECT_ID}-bucket
        image: gcr.io/{PROJECT_ID}/servicio:{TEMPLATE_VERSION}
        imagePullPolicy: Always
        
        name: servicio
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15

        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
